pipeline {
    agent any

    environment { HOME="."
		CI = 'true'
    }
    stages {

        stage ('Checkout'){
            steps{
                checkout scm
            }
        }
        stage('Deliver') {
            steps {
                sh 'bash ./TESTING_STANDARDS/APIREST/testDocker/deliver.sh'
            }
        }
	stage('Test') {
            steps {
                sh 'bash ./TESTING_STANDARDS/APIREST/testDocker/APItest/test.sh'
            }
        }
	stage('Finish') {
		    steps {
		        input message: 'Finished using the web site? (Click "Proceed" to continue)'
		        sh 'docker stop hellocontainerpip'
		    }
		}
    }
}
